version: 1.2
workflows:
  - name: CopyDataset
    subclass: WDL
    primaryDescriptorPath: /wdl/CopyDataset/CopyDataset.wdl
    readMePath: /wdl/CopyDataset/README.md
    testParameterFiles:
      - /wdl/CopyDataset.wdl

  - name: TerraWorkspaceTableToTDRIngest
    subclass: WDL
    primaryDescriptorPath: /wdl/TerraWorkspaceTableIngest/TerraWorkspaceTableIngest.wdl
    readMePath: /wdl/TerraWorkspaceTableIngest/README.md
    testParameterFiles:
      - /wdl/terraWorkspaceTableIngest.wdl

  - name: ExportDataFromSnapshotToOutputBucket
    subclass: WDL
    primaryDescriptorPath: /wdl/ExportDataFromSnapshot/ExportDataFromSnapshot.wdl
    readMePath: /wdl/ExportDataFromSnapshot/README.md
    testParameterFiles:
      - /wdl/exportDataFromSnapshot.wdl

  - name: GetAndDeleteOrphanedFilesFromDataset
    subclass: WDL
    primaryDescriptorPath: /wdl/GetAndDeleteOrphanedFilesFromDataset/GetAndDeleteOrphanedFilesFromDataset.wdl
    readMePath: /wdl/GetAndDeleteOrphanedFilesFromDataset/README.md
    testParameterFiles:
      - /wdl/GetAndDeleteOrphanedFilesFromDataset/GetAndDeleteOrphanedFilesFromDataset.wdl

  - name: RenameAndReingestFiles
    subclass: WDL
    primaryDescriptorPath: /wdl/RenameAndReingestFiles/RenameAndReingestFiles.wdl
    readMePath: /wdl/RenameAndReingestFiles/README.md
    testParameterFiles:
      - /wdl/RenameAndReingestFiles/RenameAndReingestFiles.wdl

  - name: DeleteBadStateFilesFromDataset
    subclass: WDL
    primaryDescriptorPath: /wdl/DeleteBadStateFilesFromDataset/DeleteBadStateFilesFromDataset.wdl
    readMePath: /wdl/DeleteBadStateFilesFromDataset/README.md
    testParameterFiles:
      - /wdl/DeleteBadStateFilesFromDataset/DeleteBadStateFilesFromDataset.wdl

  - name: ExportDataFromDatasetToOutputBucket
    subclass: WDL
    primaryDescriptorPath: /wdl/ExportDataFromDataset/ExportDataFromDataset.wdl
    readMePath: /wdl/ExportDataFromDataset/README.md
    testParameterFiles:
      - /wdl/ExportDataFromDataset/ExportDataFromDataset.wdl

  - name: HardCloneWorkspace
    subclass: WDL
    primaryDescriptorPath: /wdl/HardCloneWorkspace/HardCloneWorkspace.wdl
    readMePath: /wdl/HardCloneWorkspace/README.md
    testParameterFiles:
      - /wdl/HardCloneWorkspace/HardCloneWorkspace.wdl

  - name: FileExportAzureTdrToGcp
    subclass: WDL
    primaryDescriptorPath: /wdl/FileExportAzureTdrToGcp/FileExportAzureTdrToGcp.wdl
    readMePath: /wdl/FileExportAzureTdrToGcp/README.md
    testParameterFiles:
      - /wdl/FileExportAzureTdrToGcp/FileExportAzureTdrToGcp.wdl

  - name: CreateWorkspaceFileManifest
    subclass: WDL
    primaryDescriptorPath: /wdl/CreateWorkspaceFileManifest/CreateWorkspaceFileManifest.wdl
    readMePath: /wdl/CreateWorkspaceFileManifest/README.md
    testParameterFiles:
      - /wdl/CreateWorkspaceFileManifest/FileExportAzureTdrToGcp.wdl

  - name: SetUpStagingWorkspaceAndDataset
    subclass: WDL
    primaryDescriptorPath: /wdl/SetUpStagingWorkspaceAndDataset/SetUpStagingWorkspaceAndDataset.wdl
    readMePath: /wdl/SetUpStagingWorkspaceAndDataset/README.md
    testParameterFiles:
      - /wdl/SetUpStagingWorkspaceAndDataset/SetUpStagingWorkspaceAndDataset.wdl

  - name: CopyGcpToGcp
    subclass: WDL
    primaryDescriptorPath: /wdl/CopyGcpToGcp/CopyGcpToGcp.wdl
    readMePath: /wdl/CopyGcpToGcp/README.md
    testParameterFiles:
      - /wdl/CopyGcpToGcp/CopyGcpToGcp.wdl

  - name: GetGcpFileMd5
    subclass: WDL
    primaryDescriptorPath: /wdl/GetGcpFileMd5/GetGcpFileMd5.wdl
    readMePath: /wdl/GetGcpFileMd5/README.md
    testParameterFiles:
      - /wdl/GetGcpFileMd5/GetGcpFileMd5.wdl

  - name: ReUploadGcpObjectWithMd5
    subclass: WDL
    primaryDescriptorPath: /wdl/ReUploadGcpObjectWithMd5/ReUploadGcpObjectWithMd5.wdl
    readMePath: /wdl/ReUploadGcpObjectWithMd5/README.md
    testParameterFiles:
      - /wdl/ReUploadGcpObjectWithMd5/ReUploadGcpObjectWithMd5.wdl

  - name: RenameColumnsAndFilesInDataset
    subclass: WDL
    primaryDescriptorPath: /wdl/RenameColumnsAndFilesInDataset/RenameColumnsAndFilesInDataset.wdl
    readMePath: /wdl/RenameColumnsAndFilesInDataset/README.md
    testParameterFiles:
      - /wdl/RenameColumnsAndFilesInDataset/RenameColumnsAndFilesInDataset.wdl
