version: 1.2
workflows:
  - name: CopyDatasetToNewBillingProfile
    subclass: WDL
    primaryDescriptorPath: /wdl/copyDatasetToNewBillingProfile.wdl
    testParameterFiles:
      - /wdl/copyDatasetToNewBillingProfile.wdl

  - name: AnvilGcpWorkspaceToDatasetCreationAndIngest
    subclass: WDL
    primaryDescriptorPath: /wdl/AnvilGcpWorkspaceToDatasetCreationAndIngest.wdl
    testParameterFiles:
      - /wdl/AnvilGcpWorkspaceToDatasetCreationAndIngest.wdl

  - name: terraWorkspaceTableIngest
    subclass: WDL
    primaryDescriptorPath: /wdl/terraWorkspaceTableIngest.wdl
    testParameterFiles:
      - /wdl/terraWorkspaceTableIngest.wdl

  - name: exportDataFromSnapshotToBucket
    subclass: WDL
    primaryDescriptorPath: /wdl/exportDataFromSnapshot.wdl
    testParameterFiles:
      - /wdl/exportDataFromSnapshot.wdl

  - name: getFilesNotInDatasetMetadata
    subclass: WDL
    primaryDescriptorPath: /wdl/getFilesNotInDatasetMetadata.wdl
    testParameterFiles:
      - /wdl/getFilesNotInDatasetMetadata.wdl
