version: 1.2
workflows:
  - name: CopyDatasetToNewBillingProfile
    subclass: WDL
    primaryDescriptorPath: /wdl/CopyDatasetToNewBillingProfile/CopyDatasetToNewBillingProfile.wdl
    testParameterFiles:
      - /wdl/copyDatasetToNewBillingProfile.wdl

  - name: AnvilGcpWorkspaceToDatasetCreationAndIngestion
    subclass: WDL
    primaryDescriptorPath: /wdl/AnvilGcpWorkspaceToDatasetCreationAndIngest/AnvilGcpWorkspaceToDatasetCreationAndIngest.wdl
    testParameterFiles:
      - /wdl/AnvilGcpWorkspaceToDatasetCreationAndIngest.wdl

  - name: TerraWorkspaceToTableIngest
    subclass: WDL
    primaryDescriptorPath: /wdl/TerraWorkspaceTableIngest/TerraWorkspaceTableIngest.wdl
    testParameterFiles:
      - /wdl/terraWorkspaceTableIngest.wdl

  - name: ExportDataFromSnapshotToOutputBucket
    subclass: WDL
    primaryDescriptorPath: /wdl/ExportDataFromSnapshot/ExportDataFromSnapshot.wdl
    testParameterFiles:
      - /wdl/exportDataFromSnapshot.wdl

  - name: GetFilesNotPresentInDatasetMetadata
    subclass: WDL
    primaryDescriptorPath: /wdl/GetFilesNotInDatasetMetadata/GetFilesNotInDatasetMetadata.wdl
    testParameterFiles:
      - /wdl/getFilesNotInDatasetMetadata.wdl
