version: 1.2
workflows:
  - name: CopyDatasetToNewBillingProfile
    subclass: WDL
    primaryDescriptorPath: /stand_alone_terra_and_tdr/wdl/copy_dataset_to_new_billing_profile.wdl
    readMePath: /stand_alone_terra_and_tdr/wdl/copy_dataset_readme.md
    testParameterFiles:
      - /stand_alone_terra_and_tdr/wdl/copy_dataset_to_new_billing_profile.wdl

  - name: AnvilGCPWorkspaceTODatasetCreationAndIngest
    subclass: WDL
    primaryDescriptorPath: /stand_alone_terra_and_tdr/wdl/gcp_workspace_to_dataset_creation_and_ingest.wdl
    testParameterFiles:
      - /stand_alone_terra_and_tdr/wdl/gcp_workspace_to_dataset_creation_and_ingest.wdl

  - name: GCPWorkspaceToDatasetIngest
    subclass: WDL
    primaryDescriptorPath: /stand_alone_terra_and_tdr/wdl/gcp_workspace_to_dataset_ingest.wdl
    testParameterFiles:
      - /stand_alone_terra_and_tdr/wdl/gcp_workspace_to_dataset_ingest.wdl

  - name: exportDataFromSnapshotToBucket
    subclass: WDL
    primaryDescriptorPath: /stand_alone_terra_and_tdr/wdl/exportDataFromSnapshot.wdl
    testParameterFiles:
      - /stand_alone_terra_and_tdr/wdl/exportDataFromSnapshot.wdl

  - name: getFilesNotInDatasetMetadata
    subclass: WDL
    primaryDescriptorPath: /stand_alone_terra_and_tdr/wdl/get_files_not_dataset_metadata.wdl
    testParameterFiles:
      - /stand_alone_terra_and_tdr/wdl/get_files_not_dataset_metadata.wdl
