version: 1.2
workflows:
  - name: copy_dataset_to_new_billing_profile
    subclass: WDL
    primaryDescriptorPath: /stand_alone_terra_and_tdr/wdl/copy_dataset_to_new_billing_profile.wdl
    testParameterFiles:
      - /stand_alone_terra_and_tdr/wdl/copy_dataset_to_new_billing_profile.wdl

  - name: gcp_workspace_to_dataset_creation_and_ingest
    subclass: WDL
    primaryDescriptorPath: /stand_alone_terra_and_tdr/wdl/gcp_workspace_to_dataset_creation_and_ingest.wdl
    testParameterFiles:
      - /stand_alone_terra_and_tdr/wdl/gcp_workspace_to_dataset_creation_and_ingest.wdl

  - name: gcp_workspace_to_dataset_ingest
    subclass: WDL
    primaryDescriptorPath: /stand_alone_terra_and_tdr/wdl/gcp_workspace_to_dataset_ingest.wdl
    testParameterFiles:
      - /stand_alone_terra_and_tdr/wdl/gcp_workspace_to_dataset_ingest.wdl

  - name: export_data_from_snapshot_to_bucket
    subclass: WDL
    primaryDescriptorPath: /stand_alone_terra_and_tdr/wdl/export_data_from_snapshot.wdl
    testParameterFiles:
      - /stand_alone_terra_and_tdr/wdl/export_data_from_snapshot.wdl
