x-env: &env
  volumes:
    - $HOME/.config/gcloud:/gcp/config:ro
    - ./:/etc/local_repo
  environment:
    CLOUDSDK_CONFIG: /gcp/config
    GOOGLE_APPLICATION_CREDENTIALS: /gcp/config/application_default_credentials.json

services:
  dev-cromwell:
    <<: *env
    # for dev
    build:
      dockerfile: ./dev/Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
      - 8080:80
    privileged: true
    container_name: dev-cromwell
    platform: linux/amd64

  ops-toolbox-slim:
    <<: *env
    # for dev
    build:
      dockerfile: ./ops_docker_utils_slim/Dockerfile
    container_name: ops_terra_utils_slim
    stdin_open: true
    tty: true
    ports:
      - 8080:80
    entrypoint: /bin/sh
