services:
  ops-toolbox:
    # for dev
    build: .
    privileged: true
    container_name: ops_terra_utils
    volumes:
      - $HOME/.config/gcloud:/gcp/config:ro
      - ./stand_alone_terra_and_tdr:/etc/terra_utils_dev
    environment:
      CLOUDSDK_CONFIG: "/gcp/config"
      GOOGLE_APPLICATION_CREDENTIALS: "/gcp/config/application_default_credentials.json"
    stdin_open: true
    tty: true
    ports:
      - 8080:80
    entrypoint: /bin/sh
