name: Perform linting checks
description: test description

runs:
  using: 'composite'

  steps:
    - name: lint
      uses: ls-lint/action@v2.2.3
    - name: Install flake8
      run: pip install flake8
      shell: bash
    - name: Lint with flake8
      run: |
        flake8 --max-line-length=122 .
      shell: bash
