name: Perform linting checks
description: test description
inputs:
  context:
    description: 'Name of job to create/update check for'
    required: true
  status:
    description: 'Status of workflow to create/update status for'
    required: true
  job_url:
    description: 'URL to link to in status check'
    required: true



runs:
  using: 'composite'
  steps:
    - name: create status check
      id: check-creation
      env:
        GITHUB_TOKEN: ${{ github.token }}
      shell: bash
      # For prod change to -f 'head_sha=${{ github.event.pull_request.head.sha }}' \
      run: |
        gh api --method POST -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        /repos/${{ github.repository }}/statuses/${{ github.sha }} \
        -f "name=${{ inputs.context }}" \
        -f "context=${{ inputs.context }}" \
        -f "state=${{ inputs.status }}" \
        -f "target_url=${{ inputs.job_url }}"
