name: create github status check
description:

runs:
  using: 'composite'

  steps:
  - name: create github status check
    uses: actions/github-script@v7
    with:
      script: |
        github.rest.checks.create({
        owner: context.repo.owner,
        repo: context.repo.repo,
        head_sha: context.sha
            })
