name: Run Integration Tests
description: "This action runs integration tests by checking out the PR branch, setting up GCP authentication, installing dependencies, and running the tests."

inputs:
  gcp_credentials:
    description: "GCP credentials JSON for authentication"
    required: true
  python_version:
    description: "Python version to use"
    default: '3.11'
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout PR Branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Login to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ inputs.gcp_credentials }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash

    - name: Run tests
      run: |
        pip install pytest
        pytest python/tests/
      shell: bash
