name: merge validations

on:
  pull_request:
    types:
      - opened
  issue_comment:
    types:
      - created
jobs:
  E2E_linting_check:
    if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/run-tests'))
    runs-on: ubuntu-latest
    steps:
      - name: clone branch of PR
        uses: actions/checkout@v3

      - name: Perform linting checks
        uses: ./.github/actions/linting-check

  E2E_wdl_validation:
    if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/run-tests'))
    needs: E2E_linting_check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}  # This ensures it checks out the feature branch of the PR

      - name: Run WDL validation
        uses: ./.github/workflows/validate_wdls.yaml

  E2E_integration_tests:
    if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/run-tests'))
    needs: E2E_linting_check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}  # Checkout the feature branch of the PR

      - name: Run integration tests
        uses: ./.github/workflows/integration-tests.yaml
    secrets: inherit
