name: merge validations

on:
  pull_request:
    branches: [ main ]
    types: [ opened ]
  issue_comment:
    types: [ created ]

jobs:

  add_comment_to_pr:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'opened' }}
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Thank you for contributing to the ops-terra-utils repo! \n A test suite will now begin running to ensure that no breaking changes are made.\n If these tests fail you can have them re-run after making changes by commenting `/run_tests`'
            })

  linting_check:
    # only run newly created PR or comment with /run_tests
    runs-on: ubuntu-latest
    steps:
      - name: remove whitespace
        run: |
            echo "FORMATTED_COMMENT=$(echo ${{github.event.comment.body}} | tr -d "[:blank:])" >> $GITHUB_ENV
      - name: Perform linting checks
        if: ${{ github.event.action == 'opened' || env.FORMATTED_COMMENT == '/run_tests' }}
        uses: ./.github/workflows/linting_check.yaml

  wdl_validation:
    runs-on: ubuntu-latest
    needs: linting_check
    steps:
        - uses: actions/checkout@v4
        - name: find any changed wdl files
          id: get_updated_wdls
          uses: tj-actions/changed-files@v45
          with:
            files: 'wdl/**.wdl'
        - name: run_wdl_validation
          if: steps.get_updated_wdls.outputs.any_changed == 'true'
          uses: ./.github/workflows/validate_wdls.yaml

  integration_tests:
    needs: linting_check
    uses: ./.github/workflows/integration_tests.yaml
    secrets: inherit
