name: merge validations

on:
  pull_request:
    branches: [ main ]
    types: labeled

jobs:

  Remove_label:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'run-test-suite' }}
    steps:
      - name: create app token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.WORKFLOW_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}
      - name: Remove label
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'run-test-suite'
            })

  E2E_linting_check:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'run-test-suite' }}
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v4

      - name: Perform linting checks
        uses: ./.github/actions/linting-check


  E2E_wdl_validation:
    needs: E2E_linting_check
    uses: ./.github/workflows/validate_wdls.yaml

  E2E_integration_tests:
    concurrency:
      group: integration-tests
      cancel-in-progress: false
    needs: E2E_linting_check
    uses: ./.github/workflows/integration-tests.yaml
    secrets: inherit
