name: merge validations

on:
  pull_request:
    branches: [ main ]
    types: opened
  issue_comment:
    types: created
  workflow_dispatch:

jobs:

  E2E_linting_check:
    runs-on: ubuntu-latest
    steps:
      - name: Github API Request
        id: request
        uses: octokit/request-action@v2.0.2
        with:
          route: ${{ github.event.issue.pull_request.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get PR informations
        id: pr_data
        run: |
          echo "::set-output name=repo_name::${{ fromJson(steps.request.outputs.data).head.repo.full_name }}"
          echo "::set-output name=repo_clone_url::${{ fromJson(steps.request.outputs.data).head.repo.clone_url }}"
          echo "::set-output name=repo_ssh_url::${{ fromJson(steps.request.outputs.data).head.repo.ssh_url }}"

      - name: Checkout PR Branch
        uses: actions/checkout@v3
        with:
          repository: ${{fromJson(steps.request.outputs.data).head.repo.full_name}}
          ref: ${{fromJson(steps.request.outputs.data).head.ref}}


      - name: Perform linting checks
        uses: ./.github/actions/linting-check
      - name: update commit status
        if: always()
        uses: ./.github/actions/job-status-util
        with:
          context: 'E2E_linting_check'
          job_url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          status: ${{ job.status }}


  E2E_wdl_validation:
    needs: E2E_linting_check
    uses: ./.github/workflows/validate_wdls.yaml

  E2E_integration_tests:
    needs: E2E_linting_check
    uses: ./.github/workflows/integration-tests.yaml
    secrets: inherit
