name: merge validations

on:
  pull_request:
    branches: [ main ]
    types:
      - opened
  issue_comment:
    types:
      - created

jobs:
  linting_check:
    # only run newly created PR or comment with /run_tests
    if: ${{ github.event.action == 'opened' || github.event.comment.body == '/run_tests' }}
    uses: ./.github/workflows/linting_check.yaml

  wdl_validation:
    runs-on: ubuntu-latest
    needs: linting_check
    steps:
        - uses: actions/checkout@v4
        - name: find any changed wdl files
          id: get_updated_wdls
          uses: tj-actions/changed-files@v45
          with:
            files: 'wdl/**.wdl'
        - name: run_wdl_validation
          if: steps.get_updated_wdls.outputs.any_changed == 'true'
          uses: ./.github/workflows/validate_wdls.yaml
