name: Static Analysis (mypy & autopep8)

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            mypy==1.13.0 \
            autopep8==2.0.4 \
            types-requests \
            types-python-dateutil \
            types-pytz

      - name: Run mypy
        run: |
          mypy . \
            --disallow-untyped-defs \
            --disallow-incomplete-defs \
            --disallow-untyped-calls \
            --ignore-missing-imports \
            --python-version=3.11 \
            --exclude '^python/tests/'

      - name: Run autopep8 (check only)
        run: |
          autopep8 . --recursive --diff --exit-code
