

on:
  pull_request:
    branches: [ main ]
    types: opened
  issue_comment:
    types: created



jobs:
  act-on-pr-creation:
    runs-on: ubuntu-latest
    steps:
      - name: add comment to PR
        if: ${{ github.event.action == 'opened' }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'Thank you for contributing to the ops-terra-utils repo! \n A test suite will now begin running to ensure that no breaking changes are made.\n If these tests fail you can have them re-run after making changes by commenting `/run_tests`'
            })
      - name: add label
        if: ${{ github.event.action == 'opened' || contains(github.event.comment.body, '/run_tests') }}
        uses: actions/github-script@v7
        with:
            script: |
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['run-test-suite']
              })
