name: run integrtaion tests

on:
  workflow_call:

jobs:

  Run_Integration_Tests:
    runs-on: ubuntu-latest
    steps:
      - name: check for util changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            utils:
              - python/utils/**
      - name: Checkout PR Branch
        uses: actions/checkout@v3

      - name: Login to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.INTEGRATION_TEST_ACCOUNT }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        if: steps.changes.outputs.utils == 'true'
        run: |
          pip install pytest
          pytest python/tests/
      
      - name: test resource _cleanup
        if: always()
        run: | 
          python -m python.tests.utils.clean_up_test_resources.py
