name: Perform linting checks


on:
  pull_request:
    branches:
      - '*'

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: ls-lint/action@v2.2.3
            - name: Install flake8
              run: pip install flake8
            - name: Lint with flake8
              run: |
                flake8 --max-line-length=122 .
