
# This workflow validates all pipeline WDL files (those found in the pipelines/ projects/ and beta-pipelines directories) using the 'womtool' tool.
name: WomtoolCheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate_wdl_job:
    runs-on: ubuntu-latest
    name: Validate all wdl using womtool
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/checkout@v2
      - name: Run womtools
        run: |
          ./scripts/validate_wdls.sh
